// KasaiRaito All Rights Reserved

#pragma once

#include "NativeGameplayTags.h"

/**
 * 
 */

namespace HuntedGameplayTags
{
	/* Input Tags */
	/* Movement */
	HUNTED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	HUNTED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Sneak);
	HUNTED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Sprint);
	HUNTED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	HUNTED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Snap);
	HUNTED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	
	/* Abilities */
	HUNTED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Echo);
	
	/* Combat */
	HUNTED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Aim_Gun);
	HUNTED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Aim_Gun);
	HUNTED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Shoot_Gun);
	HUNTED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Shoot_Gun);
	HUNTED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Reload_Gun);
	HUNTED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Reload_Gun);

	/* Equip / Unequip */
	HUNTED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Equip_Gun);
	HUNTED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Unequip_Gun);
	HUNTED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Gun);
	HUNTED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Gun);

	/* Events */
	HUNTED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Gun);
	HUNTED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_Gun);
	HUNTED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Reload_Gun);

	/** Player Tags **/
	HUNTED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_BasicKnife);
	HUNTED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Gun);
	
	/** Enemy Tags **/
	HUNTED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Weapon);
}