// KasaiRaito All Rights Reserved

#pragma once

#include "NativeGameplayTags.h"

/**
 * 
 */

namespace HuntedGameplayTags
{
	/* Input Tags */
	HUNTED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	HUNTED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Sneak);
	HUNTED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Sprint);
	HUNTED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch);
	HUNTED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Snap);

	HUNTED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Echo);
	
	HUNTED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);

	/* Equip / Unequip */
	HUNTED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Equip_BasicKnife);
	HUNTED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Unequip_BasicKnife);

	HUNTED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Equip_Gun);
	HUNTED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Unequip_Gun)

	/** Player Tags **/
	HUNTED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_BasicKnife);
	HUNTED_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Gun)
}
